System.Collections.Generic.List.InsertRange
System.Collections.ArrayList.Clear
System.Collections.ArrayList.Clone
System.Collections.ArrayList.MemberwiseClone
System.Collections.Generic.List.MemberwiseClone
System.Collections.ArrayList.CopyTo
System.Collections.ArrayList.Count
System.Collections.ArrayList.Count
System.Collections.ArrayList.Count
System.Collections.Generic.List.Count
System.Collections.ArrayList.Equals
System.Collections.Generic.IList.Equals
System.Collections.ArrayList.new
System.Collections.Generic.List.new
System.Collections.ArrayList.new
System.Collections.ArrayList.RemoveRange
System.Collections.DictionaryEntry#rec
System.Collections.Generic.KeyValuePair#rec
System.Collections.DictionaryEntry#ret
System.Collections.Generic.KeyValuePair#ret
System.Collections.DictionaryEntry.Key
System.Collections.Generic.KeyValuePair.Key
System.Collections.DictionaryEntry.Value
System.Collections.Generic.KeyValuePair.Value
System.Collections.DictionaryEntry.Value
System.Collections.Generic.KeyValuePair.Value
System.Collections.Generic.Dictionary#arg
System.Collections.Hashtable#arg
System.Collections.Generic.Dictionary#arg
System.Collections.Hashtable#arg
System.Collections.Generic.Dictionary#arg
System.Collections.Hashtable#arg
System.Collections.Generic.Dictionary#rec
System.Collections.Hashtable#rec
System.Collections.Generic.Dictionary#rec
System.Collections.Hashtable#rec
System.Collections.Generic.Dictionary#rec
System.Collections.Hashtable#rec
System.Collections.Generic.Dictionary#ret
System.Collections.Hashtable#ret
System.Collections.Generic.Dictionary#ret
System.Collections.Hashtable#ret
System.Collections.Generic.Dictionary#ret
System.Collections.Hashtable#ret
System.Collections.Generic.Dictionary#ret
System.Collections.Hashtable#ret
System.Collections.Generic.Dictionary.Count
System.Collections.Hashtable.Count
System.Collections.Generic.Dictionary.Count
System.Collections.Hashtable.Count
System.Collections.Generic.Dictionary.new
System.Collections.Hashtable.new
System.Collections.Generic.Dictionary.new
System.Collections.Hashtable.new
System.Collections.Generic.Dictionary.new
System.Collections.Hashtable.new
System.Collections.Generic.Dictionary.new
System.Collections.Hashtable.new
System.Collections.Generic.ICollection#arg
System.Collections.ICollection#arg
System.Collections.Generic.ICollection#rec
System.Collections.ICollection#rec
System.Collections.Generic.ICollection#rec
System.Collections.ICollection#rec
System.Collections.Generic.ICollection#ret
System.Collections.ICollection#ret
System.Collections.Generic.ICollection.Count
System.Collections.ICollection.Count
System.Collections.Generic.ICollection.Count
System.Collections.ICollection.Count
System.Collections.Generic.ICollection[]
System.Collections.ICollection[]
System.Collections.Generic.ICollection[]#acc
System.Collections.ICollection[]#acc
System.Collections.Generic.ICollection[]#arg
System.Collections.ICollection[]#arg
System.Collections.Generic.ICollection[]#ret
System.Collections.ICollection[]#ret
System.Collections.Generic.IDictionary#arg
System.Collections.IDictionary#arg
System.Collections.Generic.IDictionary#rec
System.Collections.IDictionary#rec
System.Collections.Generic.IDictionary#ret
System.Collections.IDictionary#ret
System.Collections.Generic.IDictionary.Count
System.Collections.IDictionary.Count
System.Collections.Generic.IDictionary.Count
System.Collections.IDictionary.Count
System.Collections.Generic.IDictionary.Equals
System.Collections.IDictionary.Equals
System.Collections.Generic.IDictionary.Values
System.Collections.IDictionary.Values
System.Collections.Generic.IEnumerable#arg
System.Collections.IEnumerable#arg
System.Collections.Generic.IEnumerable#rec
System.Collections.IEnumerable#rec
System.Collections.Generic.IEnumerable#ret
System.Collections.IEnumerable#ret
System.Collections.Generic.IList#arg
System.Collections.IList#arg
System.Collections.Generic.IList#rec
System.Collections.IList#rec
System.Collections.Generic.IList#ret
System.Collections.IList#ret
System.Collections.Generic.IList.Contains
System.Collections.IList.Contains
System.Collections.Generic.IList.Count
System.Collections.IList.Count
System.Collections.Generic.IList.Count
System.Collections.IList.Count
System.Collections.Generic.IList.Equals
System.Collections.IList.Equals
System.Collections.Generic.IList.Insert
System.Collections.IList.Insert
System.Collections.Generic.IList[]
System.Collections.IList[]
System.Collections.Generic.IList[]#acc
System.Collections.IList[]#acc
System.Collections.Generic.IList[]#arg
System.Collections.IList[]#arg
System.Collections.Generic.IList[]#ret
System.Collections.IList[]#ret
System.Collections.Generic.SortedList#arg
System.Collections.SortedList#arg
System.Collections.Generic.SortedList#rec
System.Collections.SortedList#rec
System.Collections.Generic.SortedList#rec
System.Collections.SortedList#rec
System.Collections.Generic.SortedList#ret
System.Collections.SortedList#ret
System.Collections.Generic.SortedList#ret
System.Collections.SortedList#ret
System.Collections.Generic.SortedList.Count
System.Collections.SortedList.Count
System.Collections.Generic.SortedList.new
System.Collections.SortedList.new
System.Collections.Generic.SortedList.Values
System.Collections.SortedList.Values
System.Collections.Generic.Stack#arg
System.Collections.Stack#arg
System.Collections.Generic.Stack#rec
System.Collections.Stack#rec
System.Collections.Generic.Stack#ret
System.Collections.Stack#ret
System.Collections.Generic.Stack.Count
System.Collections.Stack.Count
System.Collections.Generic.Stack.new
System.Collections.Stack.new
System.Collections.Generics.HashSet#arg
System.Collections.Generics.HashSet#rec
System.Collections.Generics.HashSet#ret
System.Collections.Generics.HashSet.new
System.Collections.Generics.IEnumerator#arg
System.Collections.IEnumerator#arg
System.Collections.Generics.IEnumerator#rec
System.Collections.IEnumerator#rec
System.Collections.Generics.IEnumerator#ret
System.Collections.IEnumerator#ret
System.Collections.IComparer#arg
System.Collections.IComparer#rec
System.Collections.IComparer#ret
System.Collections.IDictionary.Contains
System.Console#rec
System.Convert.ToInt32
System.Convert.ToInt32
System.Int32.Parse
System.Convert.ToInt32
System.Int32.Parse
System.Convert.ToInt64
System.Int64.Parse
System.Data.SqlTypes.SqlDateTime#ret
System.Data.SqlTypes.SqlDateTime#ret
System.Data.SqlTypes.SqlDateTime.new
System.Data.SqlTypes.SqlDateTime.new
System.DateTime#arg
System.DateTime#rec
System.DateTime#ret
System.DateTime.Equals
System.DateTime.new
System.DateTime.Ticks
System.DateTime.ToString
System.DateTime[]
System.DateTime[]#acc
System.DateTime[]#ret
System.Decimal
System.Decimal
System.Decimal
System.Decimal
System.Decimal#arg
System.Decimal#arg
System.Decimal#rec
System.Decimal#rec
System.Decimal#ret
System.Decimal.Equals
System.Decimal.Multiply
System.Decimal.new
System.Decimal.Round
System.Decimal.ToString
System.Decimal[]
System.Decimal[]#acc
System.Decimal[]#ret
System.Double#arg
System.Double#rec
System.Double#ret
System.Double.CompareTo
System.Double.Equals
System.Double.IsInfinity
System.Double.IsNaN
System.Double.new
System.Double.Parse
System.Double.Parse
System.Double.Value
System.Double[]
System.Double[]#acc
System.Double[]#arg
System.Double[]#ret
System.Environment.GetEnvironmentVariable
System.Environment.GetEnvironmentVariable
System.Exception#arg
System.Exception#arg
System.Exception#arg
System.Exception#rec
System.Exception#ret
System.Exception#ret
System.Exception#ret
System.Exception#ret
System.Exception#ret
System.Exception#ret
System.Exception.InnerException
System.Exception.Message
System.Exception.new
System.Exception.new
System.Exception.new
System.Exception.new
System.Exception.new
System.Exception.new
System.Exception.StackTrace
System.Exception.ToString
System.Exception.WriteLine
System.Exception[]
System.Exception[]#acc
System.Exception[]#ret
System.FormatException#ret
System.FormatException.new
System.Globalization.CultureInfo#arg
System.Globalization.CultureInfo#rec
System.Globalization.CultureInfo#ret
System.Globalization.CultureInfo.Equals
System.Globalization.CultureInfo.new
System.Globalization.CultureInfo.ToString
System.Globalization.CultureInfo.TwoLetterISOLanguageName
System.Globalization.System.Globalization.CultureInfo.InvariantCulture
System.Guid#rec
System.Guid#ret
System.IComparable#arg
System.IComparable#rec
System.IComparable#ret
System.IComparable[]
System.IComparable[]#acc
System.IComparable[]#ret
System.IndexOutOfRangeException#ret
System.IndexOutOfRangeException#ret
System.IndexOutOfRangeException.new
System.IndexOutOfRangeException.new
System.Int16#arg
System.Int16#rec
System.Int16#ret
System.Int16.Equals
System.Int16.new
System.Int16.Parse
System.Int16.Value
System.Int16[]
System.Int16[]#acc
System.Int16[]#arg
System.Int16[]#ret
System.Int32#arg
System.Int32#rec
System.Int32#ret
System.Int32.Equals
System.Int32.new
System.Int32.ToString
System.Int32.Value
System.Int32[]
System.Int32[]#acc
System.Int32[]#arg
System.Int32[]#ret
System.Int64#arg
System.Int64#arg
System.Int64#rec
System.Int64#rec
System.Int64#ret
System.Int64#ret
System.Int64.Equals
System.Int64.new
System.Int64.new
System.Int64.Parse
System.Int64.ToString
System.Int64.ToString
System.Int64.Value
System.Int64[]
System.Int64[]
System.Int64[]#acc
System.Int64[]#acc
System.Int64[]#arg
System.Int64[]#ret
System.InvalidCastException#ret
System.InvalidCastException.new
System.InvalidOperationException#ret
System.InvalidOperationException#ret
System.InvalidOperationException#ret
System.InvalidOperationException.new
System.InvalidOperationException.new
System.InvalidOperationException.new
System.IO.BinaryWriter#arg
System.IO.BinaryWriter#rec
System.IO.BinaryWriter#ret
System.IO.BinaryWriter.BaseStream.Seek
System.IO.BinaryWriter.BaseStream.SetLength
System.IO.BinaryWriter.new
System.IO.BufferedStream#rec
System.IO.BufferedStream#rec
System.IO.BufferedStream#ret
System.IO.BufferedStream#ret
System.IO.BufferedStream.new
System.IO.BufferedStream.new
System.IO.Directory.CreateDirectory
System.IO.Directory.Exists
System.IO.FileInfo#arg
System.IO.FileInfo#rec
System.IO.FileInfo#ret
System.IO.FileInfo.Create
System.IO.FileInfo.Equals
System.IO.FileInfo.Exists
System.IO.FileInfo.Exists
System.IO.FileInfo.IsReadOnly
System.IO.FileInfo.FullName
System.IO.FileInfo.FullName
System.IO.FileInfo.LastWriteTime.Ticks
System.IO.FileInfo.Length
System.IO.FileInfo.Name
System.IO.FileInfo.Name
System.IO.FileInfo.ToString
System.IO.Path.GetFullPath
System.IO.FileInfo.new
System.IO.FileInfo[]
System.IO.FileInfo[]#acc
System.IO.FileInfo[]#arg
System.IO.FileInfo[]#ret
System.IO.FileNotFoundException#ret
System.IO.FileNotFoundException.new
System.IO.FileStream#rec
System.IO.FileStream#rec
System.IO.FileStream#ret
System.IO.FileStream#ret
System.IO.FileStream.new
System.IO.FileStream.new
System.IO.IOException#arg
System.IO.IOException#ret
System.IO.IOException.new
System.IO.IOException[]
System.IO.IOException[]#acc
System.IO.MemoryStream#arg
System.IO.MemoryStream#arg
System.IO.MemoryStream#rec
System.IO.MemoryStream#rec
System.IO.MemoryStream#ret
System.IO.MemoryStream#ret
System.IO.MemoryStream.new
System.IO.MemoryStream.new
System.IO.MemoryStream.ToArray
System.IO.MemoryStream.ToString
System.IO.Path.GetFullPath
System.IO.Stream#arg
System.IO.Stream#arg
System.IO.Stream#rec
System.IO.Stream#rec
System.IO.Stream#ret
System.IO.Stream#ret
System.IO.Stream.Read
System.IO.Stream.ReadByte
System.IO.Stream.Write
System.IO.Stream.WriteByte
System.IO.Stream[]
System.IO.Stream[]#acc
System.IO.StreamReader#rec
System.IO.StreamReader#ret
System.IO.StreamReader#ret
System.IO.StreamReader.new
System.IO.StreamReader.new
System.IO.StreamWriter#arg
System.IO.StreamWriter#rec
System.IO.StreamWriter#rec
System.IO.StreamWriter#ret
System.IO.StreamWriter#ret
System.IO.StreamWriter#ret
System.IO.StreamWriter.new
System.IO.StreamWriter.new
System.IO.StreamWriter.new
System.IO.StreamWriter.Write
System.IO.StreamWriter.WriteLine
System.IO.StringReader#rec
System.IO.StringReader#ret
System.IO.StringReader.new
System.IO.StringWriter#rec
System.IO.StringWriter#ret
System.IO.StringWriter.GetStringBuilder
System.IO.StringWriter.new
System.IO.StringWriter.ToString
System.IO.TextReader#arg
System.IO.TextReader#arg
System.IO.TextReader#rec
System.IO.TextReader#rec
System.IO.TextReader#ret
System.IO.TextReader#ret
System.IO.TextReader.new
System.IO.TextReader.Read
System.IO.TextWriter#arg
System.IO.TextWriter#arg
System.IO.TextWriter#rec
System.IO.TextWriter#rec
System.IO.TextWriter#ret
System.IO.TextWriter#ret
System.IO.TextWriter.new
System.IO.TextWriter.Write
System.IO.TextWriter.Write
System.IO.TextWriter.WriteLine
System.Math#rec
System.Math.Abs
System.Math.Ceiling
System.Math.Floor
System.Math.Log
System.Math.Max
System.Math.Min
System.Math.Pow
System.Math.Round
System.Math.Sqrt
System.Net.WebRequest#arg
System.Net.WebRequest#rec
System.Net.WebRequest#ret
System.Net.WebRequest.GetResponse
System.NotSupportedException#ret
System.NotSupportedException.new
System.NullReferenceException#ret
System.NullReferenceException.new
System.Object#arg
System.Object#rec
System.Object#ret
System.Object.Clone
System.Object.MemberwiseClone
System.Object.Equals
System.Object.GetHashCode
System.Object.GetType
System.Object.new
System.Object.Run
System.Object.ToString
System.Object[]
System.Object[]#acc
System.Object[]#arg
System.Object[]#ret
System.OutOfMemoryException#ret
System.OutOfMemoryException.new
System.Random#arg
System.Random#rec
System.Random#ret
System.Random.new
System.Random.Next
System.Random.Next
System.Reflection.Arrays#rec
System.Reflection.Arrays.Length
System.Reflection.Arrays.new
System.Reflection.Assembly#arg
System.Reflection.Assembly#rec
System.Reflection.Assembly#ret
System.Reflection.Assembly.GetType
System.Reflection.ConstructorInfo#arg
System.Reflection.ConstructorInfo#rec
System.Reflection.ConstructorInfo#ret
System.Reflection.ConstructorInfo.DeclaringType
System.Reflection.ConstructorInfo.new
System.Reflection.ConstructorInfo[]
System.Reflection.ConstructorInfo[]#acc
System.Reflection.ConstructorInfo[]#ret
System.Reflection.FieldInfo#arg
System.Reflection.FieldInfo#rec
System.Reflection.FieldInfo#ret
System.Reflection.FieldInfo.FieldType
System.Reflection.FieldInfo.GetValue
System.Reflection.FieldInfo.GetValue
System.Reflection.FieldInfo.Name
System.Reflection.FieldInfo.SetValue
System.Reflection.FieldInfo[]
System.Reflection.FieldInfo[]#acc
System.Reflection.FieldInfo[]#ret
System.Reflection.MethodInfo#arg
System.Reflection.MethodInfo#rec
System.Reflection.MethodInfo#ret
System.Reflection.MethodInfo.Name
System.Reflection.MethodInfo.ReturnType
System.Reflection.MethodInfo[]
System.Reflection.MethodInfo[]#acc
System.Reflection.MethodInfo[]#ret
System.Reflection.TargetInvocationException#rec
System.Reflection.TargetInvocationException.InnerException
System.Resources.newResourceManager
System.Resources.ResourceManager
System.Resources.ResourceManager#rec
System.Resources.ResourceManager#ret
System.Security.Cryptography.MD5#arg
System.Security.Cryptography.MD5#rec
System.Security.Cryptography.MD5#ret
System.Security.Cryptography.MD5.ComputeHash
System.Security.Cryptography.MD5.Create
System.Security.Cryptography.MD5.Hash
System.Security.Cryptography.MD5.Initialize
System.Single#arg
System.Single#rec
System.Single#ret
System.Single.CompareTo
System.Single.Equals
System.Single.IsInfinity
System.Single.IsNaN
System.Single.new
System.Single.Parse
System.Single.Parse
System.Single.ToString
System.Single.Value
System.Single[]
System.Single[]#acc
System.Single[]#arg
System.Single[]#ret
System.String#arg
System.String#arg
System.String#rec
System.String#rec
System.String#rec
System.String#ret
System.String#ret
System.String#ret
System.String.Compare
System.String.CompareOrdinal
System.String.Concat
System.String.CopyTo
System.String.Equals
System.String.Equals
System.String.GetHashCode
System.String.GetType
System.String.Length
System.String.Length
System.String.new
System.String.Replace
System.String.StartsWith
System.String.Substring
System.String.ToLower
System.String.ToString
System.String.ToString
System.String.ToString
System.String.ToString
System.String.ToUpper
System.String[]
System.String[]
System.String[]#acc
System.String[]#acc
System.String[]#arg
System.String[]#ret
System.String[]#ret
System.System.Guid.NewGuid
System.Text.Decoder#rec
System.Text.Decoder#ret
System.Text.Encoder#arg
System.Text.Encoder#rec
System.Text.Encoding#arg
System.Text.Encoding#rec
System.Text.Encoding#ret
System.Text.Encoding.Equals
System.Text.Encoding.GetDecoder
System.Text.Encoding.new
System.Text.Encoding[]
System.Text.Encoding[]#acc
System.Text.Encoding[]#arg
System.Text.Encoding[]#ret
System.Text.StringBuilder
System.Text.StringBuilder
System.Text.StringBuilder#arg
System.Text.StringBuilder#arg
System.Text.StringBuilder#rec
System.Text.StringBuilder#rec
System.Text.StringBuilder#ret
System.Text.StringBuilder#ret
System.Text.StringBuilder.Length
System.Text.StringBuilder.Length
System.Text.StringBuilder.new
System.Text.StringBuilder.new
System.Text.StringBuilder.Remove
System.Text.StringBuilder.Remove
System.Text.StringBuilder.ToString
System.Text.StringBuilder.ToString
System.Text.StringBuilder.ToString
System.Text.StringBuilder[]
System.Text.StringBuilder[]#acc
System.Text.StringBuilder[]#ret
System.Text.System.Text.Encoding.GetEncoding
System.Threading.ThreadInterruptedException#ret
System.Threading.ThreadInterruptedException.new
System.Type#arg
System.Type#rec
System.Type#ret
System.Type#ret
System.Type.Assembly
System.Type.Assembly.GetFile
System.Type.BaseType
System.Type.BaseType
System.Type.FullName
System.Type.GetElementType
System.Type.GetField
System.Type.GetFields
System.Type.GetMethods
System.Type.GetType
System.Type.IsArray
System.Type.IsInstanceOfType
System.Type.IsInterface
System.Type.IsPrimitive
System.Type.Name
System.Type.Namespace
System.Type.new
System.Type.ToString
System.Type[]
System.Type[]
System.Type[]#acc
System.Type[]#acc
System.Type[]#arg
System.Type[]#ret
System.Type[]#ret
System.Uri#arg
System.Uri#rec
System.Uri#ret
System.Uri.new
System.Uri.ToString
System.WeakReference#rec
System.WeakReference#rec
System.WeakReference#ret
System.WeakReference#ret
System.WeakReference#ret
System.WeakReference.new
System.WeakReference.new
System.WeakReference.Target
System.Web.HttpUtility#rec
if
while
do
for
throw
case
return
